name: Build Release

on:
  push:
    tags:
      - '*'
      
jobs:
  build-release:
    name: Build and Upload a release
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source
        uses: actions/checkout@v2

      - name: Create ENV
        run: |
          echo "::set-env name=REPO::$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2-)"
          echo "::set-env name=VER::$(echo $GITHUB_REF | cut -d '/' -f 3-)"
        
      - name: Build
        run: |
          npm install
          npm run-script build

      - name: Package
        run: |
          pushd build
          tar zcvf ../${{ env.REPO }}-${{ env.VER }}.tar.gz .
          popd

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VER }}
          release_name: Release ${{ env.VER }}
          draft: false
          prerelease: false
          
      - name: Upload release
        uses: PeerXu/upload-asset@v1
        with:
          file: ${{ env.REPO }}-${{ env.VER }}.tar.gz
          os: linux
          arch: amd64
          with_tag: true
          with_sha1: true
          suffix: .tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
