name: Build Release

on:
  push:
    tags:
      - '*'
      
jobs:
  build-release:
    name: Build and Upload a release
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source
        uses: actions/checkout@v2

      - name: Create ENV
        run: |
          echo "::set-env name=REPO::$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2-)"
        
      - name: Build
        run: |
          npm install
          npm run-script build

      - name: Package
        run: |
          pushd build
          tar zcvf ../${REPO}-${{ github.ref }}.tar.gz .
          popd

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ env.REPO }}-${{ github.ref }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
